name: Different Runners of action workflows
description: Testing out the different runners that an action workflow can run on

on:
  workflow_dispatch: 

jobs:
  RunOnGhRunner:
    name: Run the job Github hosted runner - regular compute instance
    runs-on: ubuntu-latest
    steps:
      - name: Run from GH runners
        run: |
              echo "GITHUB_EVENT ->  $GITHUB_EVENT"
              echo "runner.name -> ${{ runner.name }}"
              echo "runner.environment -> ${{ runner.environment }}"
              echo "runner.arch -> ${{ runner.arch }}"
              echo "runner.arch -> ${{ runner.os }}"
              

  RunOnContainer:
    name: Run the job on a Container
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Running from Alpine Container
        run: |
              echo "runner.name -> ${{ runner.name }}"
              echo "runner.environment -> ${{ runner.environment }}"
              echo "runner.arch -> ${{ runner.arch }}"
              echo "runner.arch -> ${{ runner.os }}"
    
