name: secrets and github Env variables

on:
  workflow_dispatch:

jobs:
  test1_secretsAndEnvs:
    runs-on: ubuntu-latest
    environment: test1
    env:
      INSCRIPT_ENV1 : INSCRIPT_VAL1
      INSCRIPT_ENV2 : INSCRIPT_VAL2
      
    steps:
      - name: print secrets and variables from env - test1
        run: |
              echo "test1.ENV_BASE_URL  : ${{vars.ENV_BASE_URL}}"
              echo "test1.USER_TEST1_PWD : ${{secrets.USER_TEST1_PWD}}"
              
           
      
      
      
