name: Upload and download demo
description: Upload and download demo
on: workflow_dispatch

jobs:
  uploadAnArtifact:
    name: Create and Upload an artifact using actions/upload-artifact
    runs-on: ubuntu-latest
    steps:
      - name: create a file
        run: |
              pwd
              mkdir foo
              echo "hello world" >> foo/example.txt
              ls -ltrh
              
      - name: upload the file
        uses: actions/upload-artifact@v7
        # with:
        #   path: foo/example.txt
        #   name: uploadedFile
        with:
          path: ./foo/
          name: uploadedFile

  downloadAnArtifact:
    name: Download an artifact that was created by upstream job using actions/download-artifact
    needs: uploadAnArtifact
    runs-on: ubuntu-latest

    steps:
      - name: download the artifact
        uses: actions/download-artifact@v8
        with:
          name: uploadedFile

      - name: cat the downloaded file
        run: |
              pwd
              ls -ltrh *
              cat foo/example.txt
        

              
    
